# Header
menu:
  Home: /
  Archives: /archives/
  Notebook: http://nbviewer.jupyter.org/github/superalsrk/notebook/blob/master/index.ipynb
  About: /about/


rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:

- category
- tagcloud
- friendlink




duoshuo: stackbox

# Miscellaneous
google_analytics:
favicon: /favicon.ico?v=1
twitter:
google_plus:
fb_admins:
fb_app_id:
